/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'VoiceOutput': EventHandler<unknown, never>
    'voiceInput': ApiRouteHandler<unknown, unknown, { topic: 'google.analyzequeryRequest'; data: unknown }>
    'RefundResponseHandler': EventHandler<unknown, { topic: 'voice.synthesize'; data: unknown }>
    'RefundAgent': EventHandler<unknown, { topic: 'refund.response'; data: unknown }>
    'HulkResponseHandler': EventHandler<unknown, { topic: 'voice.synthesize'; data: unknown }>
    'HavocResponseHandler': EventHandler<unknown, { topic: 'voice.synthesize'; data: unknown }>
    'getVoiceResponse': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'getResponse': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'FraudResponseHandler': EventHandler<unknown, { topic: 'voice.synthesize'; data: unknown }>
    'FraudDetector': EventHandler<unknown, { topic: 'google.refund.requested'; data: unknown } | { topic: 'fraud.response'; data: unknown }>
    'analyzeUserquery': ApiRouteHandler<unknown, unknown, { topic: 'google.analyzequeryRequest'; data: unknown }>
    'Agent_havoc': EventHandler<unknown, { topic: 'havoc.response'; data: unknown }>
    'Agent_hulk': EventHandler<unknown, { topic: 'hulk.response'; data: unknown }>
    'AnalyzeQuery': EventHandler<unknown, { topic: 'google.havocRequest'; data: unknown } | { topic: 'google.hulkRequest'; data: unknown } | { topic: 'google.fraud_detectorRequest'; data: unknown }>
  }
    
}